### ISSUE TITLE
Doc on configurations?

### ISSUE THREAD

**Issue by kawing-chiu** [Psiphon-Labs/psiphon-tunnel-core#108]
I have some trouble understanding how to make a psiphon.config for psiphon-tunnel-core. What exactly is PropagationChannelId and SponsorId and where am I supposed to get these ids from? Currently the doc only says `Replace each <placeholder> with a value from your Psiphon network.` which is vague. I googled and found nothing. It seems that on windows manual setting of these ids is unnecessary. Some explaination on the other config options would be very helpful, too.

**Comment by psiphon-admin** [comment]
The config parameters are now documented here. See https://godoc.org/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon#Config. The README has also been updated with this link.

The code for setting up your own server can be found in our main repository here: https://bitbucket.org/psiphon/psiphon-circumvention-system. This is not well documented. There is some discussion about setting up your own personal server in the developer group: https://groups.google.com/forum/#!forum/psiphon3-developers.

If you would like a psiphon-tunnel-core config file for the Psiphon Network, strictly for personal use, send a request to info@psiphon.ca.
