### ISSUE TITLE
How to build in fedora 20?

### ISSUE THREAD

**Issue by zjhxmjl** [Psiphon-Labs/psiphon-tunnel-core#76]
Hi,guys!
when i build it ,i get this error info,can you give me some advance?
[zjhxmjl@localhost psiphon]$ pwd
/home/zjhxmjl/Downloads/psiphon-tunnel-core/psiphon
[zjhxmjl@localhost psiphon]$ go build
LookupIP.go:27:2: cannot find package "github.com/Psiphon-Inc/dns" in any of:
	/usr/lib/golang/src/pkg/github.com/Psiphon-Inc/dns (from $GOROOT)
	($GOPATH not set)
dataStore.go:33:2: cannot find package "github.com/Psiphon-Inc/go-sqlite3" in any of:
	/usr/lib/golang/src/pkg/github.com/Psiphon-Inc/go-sqlite3 (from $GOROOT)
	($GOPATH not set)
socksProxy.go:27:2: cannot find package "github.com/Psiphon-Inc/goptlib" in any of:
	/usr/lib/golang/src/pkg/github.com/Psiphon-Inc/goptlib (from $GOROOT)
	($GOPATH not set)
serverApi.go:29:2: cannot find package "github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/transferstats" in any of:
	/usr/lib/golang/src/pkg/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/transferstats (from $GOROOT)
	($GOPATH not set)
meekConn.go:36:2: cannot find package "golang.org/x/crypto/nacl/box" in any of:
	/usr/lib/golang/src/pkg/golang.org/x/crypto/nacl/box (from $GOROOT)
	($GOPATH not set)
tunnel.go:35:2: cannot find package "golang.org/x/crypto/ssh" in any of:
	/usr/lib/golang/src/pkg/golang.org/x/crypto/ssh (from $GOROOT)
	($GOPATH not set)

**Comment by adam-p** [comment]
You need to set up your source directories properly, including `$GOPATH`. https://golang.org/doc/code.html#GOPATH
